### PR TITLE
Support for D struct types

### PR DESCRIPTION
**Pull request by thaven**
This PR adds support for passing D structs over DBus, if the contained types can all pass through DBus.

### CODE REVIEW

**Comment by WebFreak001** [comment]
can you add a test in a separate module so private variables aren't used it in (common source of errors in this kind of implementation) and also check private variables and static variables

**Comment by thaven** [comment]
That makes sense, though I'm not quite sure what you mean regarding static variables.

Not to duplicate stuff, I think I'll move the unittest into `ddbus.thin` and mark some of the struct fields `private`.

**Comment by WebFreak001** [comment]
Make sure static and private variables aren't included when serialized/deserialized

**Comment by thaven** [comment]
About static fields, I just naturally assumed they wouldn't be serialized because they are not in any way part of the struct (they are bound to the type itself, not the instance). I just did some tests, and my assumption seems correct.

About the private fields, I do not really agree with you. They should be serialized, as good programming style usually demands *all* fields to be private (access from other modules only through `@property` methods). Serialization is a special case that kind of hacks into the struct using reflection to get all its fields.

Unfortunately, the current implementation (but with the unit test moved into `ddbus.thin`) fails on private fields:
> source/ddbus/conv.d(294,5): Error: struct ddbus.thin.__unittestL573_23.S1 member a is not accessible
source/ddbus/conv.d(276,5): Error: template instance ddbus.conv.readIterStruct!(S1) error instantiating
source/ddbus/conv.d(294,54):        instantiated from here: readIter!(S1)
source/ddbus/conv.d(276,5):        instantiated from here: readIterStruct!(S2)
source/ddbus/thin.d(475,22):        instantiated from here: readIter!(S2)
source/ddbus/thin.d(587,6):        instantiated from here: read!(S2)

**Comment by thaven** [comment]
It works now, with private fields being marshaled. A (future) enhancement might be to have an UDA to except fields from marshaling through DBus.

E.g.:
```d
struct Foo {
    private:
    @noMarshal int localOnlyField;
    int marshaledFieldA;
    string marshaledFieldB;
}
```

**Comment by WebFreak001** [comment]
then add support for `@property` tagged methods, but private variables should never be serialized, no library does it like that and nobody expects it to because private means nothing should access it because changing it will break the program. Take a look at how painlessjson does it, it takes all public variables & property functions. There is even a library you could depend on to get the list of members to serialize/deserialze:

https://github.com/msoucy/painlesstraits
```d
pragma(msg, allPublicFieldsOrProperties!SomeContainer); // tuple("a", "b", "c", "name")
```

I think you should switch to that to be the most obvious to all users. + You will get class support with it

**Comment by trishume** [comment]
Interesting question. I don't think it's clear that there's consensus that serialization shouldn't touch private fields and that's expected. At least in Rust, `serde` serializes and deserializes private fields, and I use this all the time, on the other hand it means my serialization formats do become incompatible sometimes.

I think what you want really depends on the application. The question is, what makes sense for DBus?

I think since DBus is supposed to have public interfaces that many apps can use, it makes sense for things to be public. If you're calling someone else's interface, it should be easy to craft your struct to have public fields matching the required type, or add support for `@property` fields like @WebFreak001  suggests. If you're providing an interface then if deserialization directly uses the fields, they are public anyway through the DBus interface. If the DBus interface is meant to be private and used with ddbus on both ends, then maybe I can see private fields being useful.

Otherwise I can't think of any examples where you wouldn't want the fields of a type you use with DBus to be public or at least `@property` fields. The thing is if you want to not touch private fields, serialization is easy, but how do you deserialize something? Leaving the private fields zeroed seems wrong to me. I think it might even make sense to just warn them that they probably should make their fields public.

I'm inclined towards not serializing private fields, and giving an error or warning if you try and deserialize with them. But, if anyone has an example of a scenario with DBus where you might not want that, I could easily be convinced otherwise.

**Comment by thaven** [comment]
Okay, let's say someone creates a daemon and a library. The library is intended for use by applications to access the services provided by the daemon. The library depends on DBus to communicate with the daemon. The daemon itself also uses the library.

The library defines a struct type which is used as a parameter to some method of the DBus interface of the daemon. The struct is opaque to users of the library, so its fields are private. As @trishume already pointed out, not serializing the private fields on DBus makes us lose data. The receiver will have no clue about their intended values.

The point is: we're doing RPC here, which should function like a local call as much as possible. When a method has a struct type parameter, the struct (including private fields of course) is being copied from the caller to the callee while making the call (assuming the struct is being passed by value, as it will be over RPC). When doing RPC, we just do that copying over the wire...

**Comment by trishume** [comment]
Do people use DBus for private RPC interfaces between their own code much? Are you using it that way? I know it's used for public interfaces a lot on Linux, but I've never heard of people using it for private interfaces, that is likely just a limitation of my knowledge though.

**Comment by thaven** [comment]
People might use DBus for private interfaces, would probably be on direct connections though, not through the system/session bus. No actual cases known to me.

However, more commonly, the actual DBus interface is public, though abstracted away from the user by a library. In this case the library may want to restrict direct access to struct fields from user code, to make sure the library methods (which may, for example, contain some validity checks) are used to create struct instances and/or modify struct fields. Of course any user code may hack around that by constructing a message itself, but if so, such must have been done deliberately, and no one can blame the library/daemon developer if anything breaks because of that.

**Comment by WebFreak001** [comment]
maybe include a flag `serialize(privateFields = IncludePrivateFields.yes)(...)` so it's obvious from the auto complete & documentation then?

**Comment by trishume** [comment]
Okay, I'm convinced that you occasionally want private fields to be serialized/deserialized.

@WebFreak001's suggestion sounds fine but I'm concerned it would require a lot of API changes and work, since there's a bunch of different interfaces.

One I idea I had is to make private fields opt-in, but easily so, with a UDA. So normally serializing would ignore private fields (or maybe error?) and deserializing will error if the struct contains private fields, but you can tag a struct with `@DBusPrivate`  to enable serializing/deserializing private fields for that struct. That sounds like it might be easy to add.

If both features turn out to be difficult I'm also fine with just always (de)serializing private fields. I don't think it will be that common that people will have a struct that they want to ignore private fields on when they serialize it, and if they do they can just add a helper struct like `MyStructDBus`, and a method to create them, that only includes the fields they want serialized.

**Comment by WebFreak001** [comment]
I like the UDA approach because it is easy to do by calling std.traits.HasUDA (addition from a few compiler versions ago). Though if an error was thrown it should happen at compile time and not at runtime, but I think most people actually just use structs with all public members for serializers/deserializers

**Comment by thaven** [comment]
I also prefer the UDA approach. I'll work on that later this week.

**Comment by thaven** [comment]
FYI @WebFreak001: Including properties is not going to work (or at least not reliably), because in DBus a struct is marshaled as just its contained values, and when including properties, we'll have to depend on traits that return member names in undefined order.

**Comment by WebFreak001** [comment]
the return order is always undefined, not just to properties. But for a struct or a non-inheriting class dmd just goes through them in the order you defined them in so I think properties can be used there just as normal member variables.

**Comment by thaven** [comment]
I use `.tupleof` now. This returns fields in order, but no properties. So to add support for properties, I'd have to modify the implementation to using traits. I know current DMD seems to retain the order of definition there, but there is no guarantee about the future, or about other compiler implementations.

And as I am typing this, I realize that the order of (property) methods in a struct is usually irrelevant, because its storage layout is dictated by the order of fields. Most structs will be defined with all fields grouped together and methods grouped together. So in 
```d
struct Foo {
  private int _a;
  int b;
  int c;

  int a() const @property {
    return _a;
  }
}

Foo f;

Message msg = Message( /* ... */ );
msg.build(f);
```
you end up with `f` being written as `tuple(f.b, f.c, f.a)`, which may not be what anyone would expect...

Also, I have had some parts implemented with traits, and keep running into trouble with that. Things like getting compiler errors about some member not being accessible while trying to check its accessibility. Such works just fine with `.tupleof`.

**Comment by thaven** [comment]
`@dbusMarshaling` was intended to allow more flags either now or in the future. I initially also had `MarshalingFlag.includeProperties`, but removed that (see previous comments).

**Review by trishume — APPROVED** [review]
Looks good to me. And you even threw in the ability to manually mark things as marshalled/not!

**Pull request merged**
