### PR TITLE
Replace body with do.

### PR DESCRIPTION
**Pull request by kubo39**

### CODE REVIEW

**Review by WebFreak001 — APPROVED** [review]

**Comment by thaven** [comment]
Hmm, I was totally unaware of this language change. Turns out it was introduced in D 2.075, though a changelog entry was forgotten. Anyway, since this will fail to compile on DMD < 2.075, i think it might be a bit early to merge this immediately. I am still working on some stuff that will require Phobos >= 2.076, so I suggest keeping this PR around to merging this around the time that gets in. 

@kubo39: thanks for making me aware of this.

**Comment by WebFreak001** [comment]
huh I thought that got added in D 2.074

**Comment by WebFreak001** [comment]
@thaven how about now?

**Comment by thaven** [comment]
Yes, that's okay.

**Review by WebFreak001 — APPROVED** [review]

**Pull request merged**
