### PR TITLE
Fixed DBusAny skipping values after string or bool

### PR DESCRIPTION
**Pull request by WebFreak001**
Fixes the bug introduced in #10

### CODE REVIEW

**Comment by trishume** [comment]
Thanks, good clean fix. I'll release v2.1.0

**Comment by WebFreak001** [comment]
Don't forget to put out a new release please ^^

**Comment by trishume** [comment]
Done

**Comment by WebFreak001** [comment]
You can also trigger an update on code.dlang.org if you don't want to wait for an hour before it's finally available

**Comment by trishume** [comment]
@WebFreak001 I've given you collaborator permission on this repo so that if you want to fix anything and I'm busy you can merge PRs and create releases yourself. 

I'd still prefer you submit PRs, but if I don't get around to reviewing them for a while feel free to merge them yourself. I can't test the code and I haven't used D in a while, so you're probably better at it than me.

**Pull request merged**
